// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	orderv1 "github.com/Nikitosnim/protos/gen/go/order"
	gomock "github.com/golang/mock/gomock"
)

// MockCrud is a mock of Crud interface.
type MockCrud struct {
	ctrl     *gomock.Controller
	recorder *MockCrudMockRecorder
}

// MockCrudMockRecorder is the mock recorder for MockCrud.
type MockCrudMockRecorder struct {
	mock *MockCrud
}

// NewMockCrud creates a new mock instance.
func NewMockCrud(ctrl *gomock.Controller) *MockCrud {
	mock := &MockCrud{ctrl: ctrl}
	mock.recorder = &MockCrudMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrud) EXPECT() *MockCrudMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCrud) Create(ctx context.Context, item string, quan int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item, quan)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCrudMockRecorder) Create(ctx, item, quan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCrud)(nil).Create), ctx, item, quan)
}

// Delete mocks base method.
func (m *MockCrud) Delete(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCrudMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCrud)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCrud) Get(ctx context.Context, id string) (*orderv1.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*orderv1.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCrudMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCrud)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockCrud) List(ctx context.Context) ([]*orderv1.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*orderv1.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCrudMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCrud)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCrud) Update(ctx context.Context, id, item string, quan int32) (*orderv1.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, item, quan)
	ret0, _ := ret[0].(*orderv1.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCrudMockRecorder) Update(ctx, id, item, quan interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCrud)(nil).Update), ctx, id, item, quan)
}
